name: Remove .env from history automatically

on:
  push:
    branches:
      - main  # או ענף אחר

jobs:
  remove-env-history:
    runs-on: ubuntu-latest  # GitHub Actions יפעיל את ה־workflow על סביבה מנוהלת
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3  # שולף את המאגר

      - name: Set up Python and install git-filter-repo
        run: |
          # התקנת Python אם הוא לא קיים
          sudo apt-get install python3-pip
          pip install git-filter-repo  # התקנה של הכלי

      - name: Remove .env from history using git-filter-repo
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # הפעלת git filter-repo למחיקת .env
          git filter-repo --path .env --invert-paths --force  # מחיקת כל ההיסטוריה של הקובץ

      - name: Commit changes and force push
        run: |
          git add .
          git commit -m "Remove .env from history"
          git push origin main --force  # דחיפת השינויים עם --force
